In [1]:
import pandas as pd

In [2]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in g:\programdata\lib\site-packages (1.4.4)
Requirement already satisfied: pytz>=2020.1 in g:\programdata\lib\site-packages (from pandas) (2022.1)
Requirement already satisfied: numpy>=1.18.5 in g:\programdata\lib\site-packages (from pandas) (1.21.5)
Requirement already satisfied: python-dateutil>=2.8.1 in g:\programdata\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: six>=1.5 in g:\programdata\lib\site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
df = pd.read_csv("services.csv")

In [4]:
df.head()

,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
0,1,1,NaN,NaN,NaN,Walk in or apply by phone.,"Older adults age 55 or over, ethnic minorities...",A walk-in center for older adults that provide...,"Age 55 or over for most programs, age 60 or ov...",NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Fair Oaks Adult Activity Center,NaN,Colma,active,No wait.,NaN,NaN
1,2,2,NaN,NaN,NaN,Apply by phone for an appointment.,Residents of San Mateo County age 55 or over,Provides training and job placement to eligibl...,"Age 55 or over, county resident and willing an...",NaN,...,NaN,"EMPLOYMENT/TRAINING SERVICES, Job Development,...",NaN,Second Career Employment Program,NaN,San Mateo County,active,Varies.,NaN,NaN
2,3,3,NaN,NaN,NaN,Phone for information (403-4300 Ext. 4322).,Older adults age 55 or over who can benefit fr...,Offers supportive counseling services to San M...,Resident of San Mateo County age 55 or over,NaN,...,NaN,"Geriatric Counseling, Older Adults, Gay, Lesbi...",NaN,Senior Peer Counseling,NaN,San Mateo County,active,Varies.,NaN,NaN
3,4,4,NaN,NaN,NaN,Apply by phone.,"Parents, children, families with problems of c...",Provides supervised visitation services and a ...,None,NaN,...,NaN,"INDIVIDUAL AND FAMILY DEVELOPMENT SERVICES, Gr...",NaN,Family Visitation Center,NaN,San Mateo County,active,No wait.,NaN,NaN
4,5,5,NaN,NaN,NaN,Phone for information.,Low-income working families with children tran...,Provides fixed 8% short term loans to eligible...,Eligibility: Low-income family with legal cust...,NaN,...,NaN,"COMMUNITY SERVICES, Speakers, Automobile Loans",NaN,Economic Self-Sufficiency Program,NaN,San Mateo County,active,NaN,NaN,NaN

In [5]:
df.head(3)

,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
0,1,1,NaN,NaN,NaN,Walk in or apply by phone.,"Older adults age 55 or over, ethnic minorities...",A walk-in center for older adults that provide...,"Age 55 or over for most programs, age 60 or ov...",NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Fair Oaks Adult Activity Center,NaN,Colma,active,No wait.,NaN,NaN
1,2,2,NaN,NaN,NaN,Apply by phone for an appointment.,Residents of San Mateo County age 55 or over,Provides training and job placement to eligibl...,"Age 55 or over, county resident and willing an...",NaN,...,NaN,"EMPLOYMENT/TRAINING SERVICES, Job Development,...",NaN,Second Career Employment Program,NaN,San Mateo County,active,Varies.,NaN,NaN
2,3,3,NaN,NaN,NaN,Phone for information (403-4300 Ext. 4322).,Older adults age 55 or over who can benefit fr...,Offers supportive counseling services to San M...,Resident of San Mateo County age 55 or over,NaN,...,NaN,"Geriatric Counseling, Older Adults, Gay, Lesbi...",NaN,Senior Peer Counseling,NaN,San Mateo County,active,Varies.,NaN,NaN

In [6]:
# check the last five record
df.tail()

,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
18,19,19,NaN,NaN,NaN,Call for screening appointment (650-347-3648).,NaN,Provides free medical and dental care to those...,Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,San Mateo Free Medical Clinic,NaN,"Belmont, Burlingame",active,Varies.,NaN,NaN
19,20,20,NaN,NaN,NaN,Walk in.,NaN,no unrequired fields for this service,NaN,NaN,...,NaN,NaN,NaN,Service with blank fields,NaN,NaN,defunct,NaN,NaN,NaN
20,21,21,NaN,NaN,NaN,By phone during business hours.,NaN,just a test service,NaN,NaN,...,NaN,NaN,NaN,Service for Admin Test Location,NaN,San Mateo County,inactive,NaN,NaN,NaN
21,22,22,NaN,"Cash, Check, Credit Card",Fotos para pasaportes,Walk in or apply by phone or mail,"Profit and nonprofit businesses, the public, m...",[NOTE THIS IS NOT A REAL SERVICE--THIS IS FOR ...,None,passports@example.org,...,We offer 3-way interpretation services over th...,"Salud, Medicina",Spanish,Passport Photos,Government-issued picture identification,"Alameda County, San Mateo County",active,No wait to 2 weeks.,http://www.example.com,"105, 108, 108-05, 108-05-01, 111, 111-05"
22,23,22,NaN,NaN,NaN,Walk in or apply by phone or mail,"Second service and nonprofit businesses, the p...",[NOTE THIS IS NOT A REAL ORGANIZATION--THIS IS...,None,NaN,...,NaN,"Ruby on Rails/Postgres/Redis, testing, wic",NaN,Example Service Name,NaN,"San Mateo County, Alameda County",active,No wait to 2 weeks,http://www.example.com,NaN

In [7]:
df.tail(1)

,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
22,23,22,NaN,NaN,NaN,Walk in or apply by phone or mail,"Second service and nonprofit businesses, the p...",[NOTE THIS IS NOT A REAL ORGANIZATION--THIS IS...,None,NaN,...,NaN,"Ruby on Rails/Postgres/Redis, testing, wic",NaN,Example Service Name,NaN,"San Mateo County, Alameda County",active,No wait to 2 weeks,http://www.example.com,NaN

In [8]:
type(df)

pandas.core.frame.DataFrame

In [9]:
# check the columns names
df.columns

Index(['id', 'location_id', 'program_id', 'accepted_payments',
       'alternate_name', 'application_process', 'audience', 'description',
       'eligibility', 'email', 'fees', 'funding_sources',
       'interpretation_services', 'keywords', 'languages', 'name',
       'required_documents', 'service_areas', 'status', 'wait_time', 'website',
       'taxonomy_ids'],
      dtype='object')

In [10]:
# columns in list format
list(df.columns)

['id',
 'location_id',
 'program_id',
 'accepted_payments',
 'alternate_name',
 'application_process',
 'audience',
 'description',
 'eligibility',
 'email',
 'fees',
 'funding_sources',
 'interpretation_services',
 'keywords',
 'languages',
 'name',
 'required_documents',
 'service_areas',
 'status',
 'wait_time',
 'website',
 'taxonomy_ids']

In [11]:
# check the data for particular column
df["description"]

0     A walk-in center for older adults that provide...
1     Provides training and job placement to eligibl...
2     Offers supportive counseling services to San M...
3     Provides supervised visitation services and a ...
4     Provides fixed 8% short term loans to eligible...
5     A multipurpose center offering a wide variety ...
6     Rosener House is a day center for older adults...
7     Delivers a hot meal to the home of persons age...
8     Provides general reading material, including b...
9     Provides general reading and media materials, ...
10    Provides general reading materials, including ...
11    Offers an intergenerational literacy program f...
12    Provides general reading materials, including ...
13    Provides food, clothing, bus tokens and shelte...
14    Provides a long-term (6-12 month) residential ...
15    Provides emergency assistance including food a...
16    Provides emergency food, clothing and furnitur...
17    By appointment only, Project Smile provides a ...
18    Provides free medical and dental care to those...
19                no unrequired fields for this service
20                                  just a test service
21    [NOTE THIS IS NOT A REAL SERVICE--THIS IS FOR ...
22    [NOTE THIS IS NOT A REAL ORGANIZATION--THIS IS...
Name: description, dtype: object

In [12]:
# dataframe: multiple records or columns
# series: a) equivalent to list
# b) In series shows the Index. ex: 1     Provides training and job placement to eligibl
type(df["description"])

pandas.core.series.Series

In [13]:
# cloumns passed in list, data type will be dataframe
df[['status']]

type(df[['status']])

pandas.core.frame.DataFrame

In [14]:
# select multiple columns
# In multiple columns case , pass the data in list format
df[['accepted_payments','application_process','audience']]

,accepted_payments,application_process,audience
0,NaN,Walk in or apply by phone.,"Older adults age 55 or over, ethnic minorities..."
1,NaN,Apply by phone for an appointment.,Residents of San Mateo County age 55 or over
2,NaN,Phone for information (403-4300 Ext. 4322).,Older adults age 55 or over who can benefit fr...
3,NaN,Apply by phone.,"Parents, children, families with problems of c..."
4,NaN,Phone for information.,Low-income working families with children tran...
5,NaN,Walk in or apply by phone for membership appli...,Any age
6,NaN,"Apply by phone or be referred by a doctor, soc...","Older adults who have memory or sensory loss, ..."
7,NaN,Apply by phone.,"Senior citizens age 60 or over, disabled indiv..."
8,NaN,Walk in. Proof of residency in California requ...,"Ethnic minorities, especially Spanish speaking"
9,NaN,Walk in. Proof of California residency to rece...,NaN
10,NaN,Walk in. Proof of California residency require...,NaN
11,NaN,"Walk in or apply by phone, email or webpage re...","Adults, parents, children in 1st-12th grades i..."
12,NaN,Walk in. Proof of California residency require...,NaN
13,NaN,Call for appointment. Referral from human serv...,Individuals or families with low or no income ...
14,NaN,Walk in or through other agency referral.,Adult alcoholic/drug addictive men and women w...
15,NaN,"Walk in. Written application, identification r...",NaN
16,NaN,Call for information.,NaN
17,NaN,Call for screening appointment. Medical visits...,NaN
18,NaN,Call for screening appointment (650-347-3648).,NaN
19,NaN,Walk in.,NaN
20,NaN,By phone during business hours.,NaN
21,"Cash, Check, Credit Card",Walk in or apply by phone or mail,"Profit and nonprofit businesses, the public, m..."
22,NaN,Walk in or apply by phone or mail,"Second service and nonprofit businesses, the p..."

In [15]:
df.dtypes

id                           int64
location_id                  int64
program_id                 float64
accepted_payments           object
alternate_name              object
application_process         object
audience                    object
description                 object
eligibility                 object
email                       object
fees                        object
funding_sources             object
interpretation_services     object
keywords                    object
languages                   object
name                        object
required_documents          object
service_areas               object
status                      object
wait_time                   object
website                     object
taxonomy_ids                object
dtype: object

In [16]:
# reead the from excel sheet
df1 = pd.read_excel("LUSID Excel - Setting up your market data.xlsx")

In [17]:
type(df1)

pandas.core.frame.DataFrame

In [18]:
df1.dtypes

Unnamed: 0    float64
Unnamed: 1    float64
Unnamed: 2    float64
Unnamed: 3     object
Unnamed: 4     object
Unnamed: 5     object
Unnamed: 6    float64
Unnamed: 7     object
Unnamed: 8     object
Unnamed: 9     object
dtype: object

In [19]:
df1.columns

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9'],
      dtype='object')

In [20]:
df1[['Unnamed: 6']]

    Unnamed: 6
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
5          NaN
6          NaN
7          NaN
8          NaN
9          NaN
10         NaN
11         NaN
12         NaN
13         NaN
14         NaN
15         NaN
16         NaN
17         NaN
18         NaN
19         NaN
20         NaN
21         NaN
22         NaN
23         NaN
24         NaN
25         NaN
26         NaN
27         NaN

In [21]:
type(df1[['Unnamed: 6']])

pandas.core.frame.DataFrame

In [22]:
# read data from the link
df2 = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")

URLError: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>

In [37]:
import lxml
import pandas as pd

In [38]:
pip install lxml

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: lxml in g:\programdata\lib\site-packages (4.9.1)
Note: you may need to restart the kernel to use updated packages.

In [39]:
# read html data
url_data = pd.read_html("https://www.basketball-reference.com/teams/GSW/2015.html")

In [40]:
type(url_data)

list

In [41]:
# number of data store in list
len(url_data)

7

In [51]:
df3  = url_data[0]

In [52]:
df3

,No.,Player,Pos,Ht,Wt,Birth Date,Unnamed: 6,Exp,College
0,19,Leandro Barbosa,SG,6-3,194,"November 28, 1982",br,11,NaN
1,40,Harrison Barnes,SF,6-8,225,"May 30, 1992",us,2,UNC
2,12,Andrew Bogut,C,7-0,260,"November 28, 1984",au,9,Utah
3,30,Stephen Curry,PG,6-2,185,"March 14, 1988",us,5,Davidson
4,31,Festus Ezeli,C,6-11,255,"October 21, 1989",ng,1,Vanderbilt
5,23,Draymond Green,PF,6-6,230,"March 4, 1990",us,2,Michigan State
6,7,Justin Holiday,SG,6-6,180,"April 5, 1989",us,1,Washington
7,9,Andre Iguodala,SF,6-6,215,"January 28, 1984",us,10,Arizona
8,1,Ognjen KuzmiÄ‡,C,7-1,251,"May 16, 1990",ba,1,NaN
9,10,David Lee,PF,6-9,245,"April 29, 1983",us,9,Florida
10,34,Shaun Livingston,PG,6-7,192,"September 11, 1985",us,9,NaN
11,20,James Michael McAdoo,PF,6-9,230,"January 4, 1993",us,R,UNC
12,4,Brandon Rush,SG,6-6,220,"July 7, 1985",us,6,Kansas
13,5,Marreese Speights,C,6-10,255,"August 4, 1987",us,6,Florida
14,11,Klay Thompson,SG,6-6,215,"February 8, 1990",us,3,Washington State

In [53]:
df3.heads()

AttributeError: 'DataFrame' object has no attribute 'heads'

In [54]:
df3.dtypes

No.            int64
Player        object
Pos           object
Ht            object
Wt             int64
Birth Date    object
Unnamed: 6    object
Exp           object
College       object
dtype: object

In [55]:
type(df3[["age"]])

KeyError: "None of [Index(['age'], dtype='object')] are in the [columns]"

In [30]:
df3.to_csv()

AttributeError: 'list' object has no attribute 'to_csv'

In [56]:
df3.columns[0]

'No.'

In [47]:
df3.tail(3)

AttributeError: 'list' object has no attribute 'tail'

In [57]:
df3[['Pos', 'Age', 'Tm']]

KeyError: "['Age', 'Tm'] not in index"

In [59]:
# STORE DATA IN SYSTEM
df3.to_csv("players_data.csv")

In [60]:
# REMOVE HEAD FORM DATA
df3.to_csv("players_data.csv",index = False)